name: Merge Pull Request
on:
  push:
    branches:
      - main
jobs:
  - build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    - name: Set up JDK 1.8
        uses: actions/setup-java@v3
      with:
        java-version: 1.8
    - name: Build with Maven
      run:
        mvn -B package --file pom.xml
  - publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up deployment
        uses: actions/setup-java@v3
        with:
          java-version: 1.8
          server-id: packagecloud
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}