# Release job
name: Release

on:
  push:
    branches: [ main ]

jobs:
  runTests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v2.3.4
  
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 8
          server-id: github

      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Publish JAR
        run:
          echo "::set-env name=PR_NUMBER::$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")"
          ./mvnw -Drevision=${{ github.event.pull_request.number }} -B release:prepare release:perform
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
